#build 

FROM node:20.19 AS build

WORKDIR /app
COPY frontend/package*.json ./
RUN npm install 
COPY frontend/ .
RUN npm run build


#run time 

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

