name: Frontend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'frontend/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest   # workflow run hone wala OS

    steps:
      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Docker Build + Push
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest -f frontend/Dockerfile.frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest

      # 7. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Docker Image (frontend)
#         run: |
#           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest -f frontend/Dockerfile.frontend .
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest

#   deploy:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     steps:
#       - name: Deploy to EC2 (frontend)
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
#             docker stop frontend || true
#             docker rm frontend || true
#             docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest


